path: .dlls
include:
  - axios
  - bluebird
  - classlist-polyfill
  - classnames
  - core-js
  - es6-error
  - jquery
  - history
  - moment
  - prop-types
  - react
  - react-dom
  - react-redux
  - react-router
  - react-router-redux
  - redux
  - redux-devtools-extension
  - redux-form
  - redux-immutable-state-invariant
  - redux-responsive
  - redux-thunk
  - regenerator-runtime
  - reselect
  - sha.js