root: true
parser: babel-eslint
presets:
extends:
  - plugin:jsx-control-statements/recommended
plugins:
  - jsx-control-statements
rules:
  react/jsx-no-undef: [error, { allowGlobals: true }]
  jsx-control-statements/jsx-jcs-no-undef: error
  jsx-control-statements/jsx-use-if-tag: error
  jsx-control-statements/jsx-otherwise-once-last: error
  jsx-control-statements/jsx-if-require-condition: error
  jsx-control-statements/jsx-when-require-condition: error
  no-restricted-syntax: [error, {
    selector: 'JSXOpeningElement[name.name=For]',
    message: 'No JSX For tags'
  }, {
    selector: 'JSXOpeningElement[name.name=With]',
    message: 'No JSX With tags'
  }]
settings:
  import/resolver:
    webpack:
      config: webpack/config.prod.babel.js